### ISSUE TITLE
Missing label for additional languages

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-evaluation-tools-list#125]
> Missing label for select that pops up when adding more than one language
> 
> For the first language we have
> 
> ```
> <label for="language_1" class="label specialField">Language<span>(Required)</span></label>
> ```
> But when you press the "Add new language" button and the second select pops up there's no label for it.

There is actually a label, it just has no content:

```
<label for="language_[n]" class="label-input"></label>
```

This label should have some content and the id should change for each label added. So first additional language should be:

```
<label for="language_2" class="label-input">Language 2</label>
```

Seccond additional language:

```
<label for="language_3" class="label-input">Language 3</label>
```

Etc

**Comment by mhansma96** [comment]
@iadawn I added a fix that solves both language block related problems in the submission form. 

There might just be one more thing to think about on this issue: when you keep counting for adding new languages: for example add language_2 and language_3, and then you remove language_2 -> adding a new language will then become the 3rd language again so you would add another language_3 in that situation. 

I have solved this by using a separate counter that just checks the number on the last added language and then does a +1. Meaning you can never have 2 of the same IDs, but this does raise a question: is it okay that when you add maybe 5 languages and then remove 2 and 3, you have language 1, 4 and 5 left. I felt like that is not ideal, but re-calculating the IDs is even more of a pain, and also very annoying for users because the content will update and that can cause confusion I think

**Comment by iadawn** [comment]
@mhansma96 See comment in the commit 1ad9495

**Comment by mhansma96** [comment]
Fixed! Thanks for the input! @iadawn 
That only leaves the removing-situation described in my previous comment

**Comment by iadawn** [comment]
> is it okay that when you add maybe 5 languages and then remove 2 and 3, you have language 1, 4 and 5 left. I felt like that is not ideal, but re-calculating the IDs is even more of a pain, and also very annoying for users because the content will update and that can cause confusion I think

The best way to address this would be to add the selected language to the label. This would need to be done onchange of the ```<select>``` but would get over the problem. I am not sure how much value that would add though compared to the additional noise from having the language name in the select box as well as in the remove button.

Thinking about it a cleaner, and easier way to do this would be to use ```aria-labelledby``` with two ids: an id on the button (which would add 'Remove') and the id from the ```<select>``` (which would add the selected langage).

**Comment by mhansma96** [comment]
The commit above adds the language in the aria-label so that its all mentioned only once. Hopefully this is what we are looking for!
