### ISSUE TITLE
Improve <abbr> presentation

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-evaluation-tools-list#127]
Abbreviations are using a pattern where the abbreviation is explained with an information icon following it. This is a bit peculiar in itself but interacting with the icon adds additional text to a ```span``` within the ```abbr``` element that just adds more confusion.

```html
<abbr title="International - Web Content Accessibility Guidelines 2.2" class="toggletip-container">
   <img alt="International - Web Content Accessibility Guidelines 2.2" tabindex="0" data-toggletip-content="International - Web Content Accessibility Guidelines 2.2" src="/content-images/wai-evaluation-tools-list/info.png">
   <span class="toggletip-span-inline" role="status"></span>
</abbr>
```

A far simpler apparoach is to present abbreviations as:

```html
<abbr title="Web Content Accessibility Guidelines">WCAG</abbr> 2.2
```

**Comment by mhansma96** [comment]
In the commit above, all abbr tags have been changed from icons to the full text before the icon, the icon with titles and hovers is therefore removed and the structure in the simpler approach as presented has been used. This has been done in the filterlist and submission form.

**Comment by iadawn** [comment]
Hmm... it is unfortunate that it is the whole label that is marked with the abbreviation. For example, 

```html
<abbr title="Continuous Integration">Command-line / CI</abbr>
```

The abbreviation is for 'CI' so the code should really be:

```html
Command-line / <abbr title="Continuous Integration">CI</abbr>
```

However, the data source and set up is not designed in this way. Would it be simpler to just change the content of the JSON to include the ```<abbr>``` element in that?

**Comment by iadawn** [comment]
@mhansma96 Not sure if the above commit will work, but that is what I was thinking?

**Comment by mhansma96** [comment]
It could work if we make sure that every time we have to print/display the title, it converts the HTML instead of just showing it. By default it might already work so that could be a solution. There might only be 2 other problems with this:

1. Now every time we want to show or we need the title, we also have the <abbr> included. This could lead to problems in the future with displaying the title. Basically it makes the title field tailored for showing the <abbr> useless for other scenarios. We might be hitting a general bad practice, even though it might work for us for now.
2. I think the filters use the ID for comparing and filtering, but we might run into issues with sorting and stuff because I imagine there could be situations where you now want to compare the terms "Command-line CI" with "Command-line / <abbr title="Continuous Integration">CI</abbr>" which will not match anymore.

Going this route might need some extra thinking or work because in general, the title field should just contain the title field. Not sure yet if we can improve the unfortunate outcome easily.

**Comment by mhansma96** [comment]
In the commit above I tried the following approach: use the INFO field in the JSON as the field that holds the title and the <abbr> while the TITLE just holds the plain title. In both the filterpage and the submissionpage, you either show the tools INFO field, if there is one, and show the TITLE if not. 

This way, all the filtering and matching, that somehow already broke after your commit that made a few small changes as an example, works again. And all info fields are displayed as they should. Only thing left is to check it a bit and maybe change what you think should be part of the <abbr> tag and what should be outside of it. 

Hopefully this is a reasonable approach!
