### ISSUE TITLE
[Filters] Collapse widget not clear when using JAWS

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-evaluation-tools-list#43]
The show/hide widgets for filter elements do not use `aria-expanded` or `aria-controls`.

I checked with JAWS to see if there was something else going on and the functionality was even less clear. When using JAWS I tabbed to a filter heading and it read out that the element was a checkbox. Pressing 'return' resulted in the first item in the checkbox group associated with the heading being selected.  Not sure if this is common JAWS or screen reader functionality or peculiar to my set up.

**Comment by iadawn** [comment]
The `<fieldset>` seems to be using a `collapsed` attribute... not sure that is a thing?

**Comment by carlosapaduarte** [comment]
VO on Safari, here.

The behaviour is similar to what @iadawn described. If the group is selected, activating checks the first checkbox, which is an unexpected behaviour. If I navigate to the legend and activate it, it collapses the group, which is also unexpected because there is no indication about that (the legend is announced as text, so it should not be interactive). Furthermore, the expand/collapse symbol is hidden from AT, so users will not even be aware that there is the possibility to hide a filter group.

**Comment by mhansma96** [comment]
Some changes have been made to the page in the meantime, does this issue still persist?
