### ISSUE TITLE
[Course list] Update or report tool

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-evaluation-tools-list#49]
Not sure what the update information or report tool links are meant to do. The links (open in a new window without mentioning it) go to the tool website it seems. Not sure whether there is functionality I am missing or if this is as intended. If the latter, then it doesn't really do what the link suggests.

**Comment by carlosapaduarte** [comment]
I would expect the update to take me to the submission form (pre-filled with the current information) so that I could update the information.

I would expect the report to take me to a different form where I could describe what is incorrect in the provided information. 

If these are not implemented, they should not be presented until the functionalities are developed.

**Comment by VeraLange** [comment]
These links have been removed for now. They might come back in later iterations.
