### ISSUE TITLE
Restore ACT Implementation filter

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wai-evaluation-tools-list#76]
On an earlier version of the tool, a filter was available to filter tools that have an ACT implementation. This should be restored. This filter can be a single checkbox that hides tools without an ACT implementation, similar to how  the Accessibility statement filter hides tools without an accessibility statement. I suggest the following wording:

Heading: ACT Implementation
Help: Rules for harmonized WCAG and ARIA testing
Label: Documented support for ACT Rules 

![Screenshot of proposed design](https://user-images.githubusercontent.com/530687/195072175-63ff4858-8ad5-4ed0-a81a-81af4e339822.png)

**Comment by bakkenb** [comment]
+1 to filter as described above. As agreed, this should be added after sufficient time has passed for community awareness of ACT Rules and Implementation reports.

**Comment by carlosapaduarte** [comment]
But wouldn't adding it as soon as possible contribute to increasing the awareness to ACT rules? I believe that increasing awareness to ACT rules would be a target for WAI :-)

**Comment by WilcoFiers** [comment]
@bakkenb That's not my recollection of what we had discussed. I believe the concern was raised that vendors should have enough time to get their tools listed as ACT implementations. My answer to that is that we've been actively recruiting implementors for over 5 years. I'm confident to say all major tool vendors know about ACT rules. I don't think there's no awareness problem there. They've been aware for years, and from talking to them I believe most of them use ACT rules (at least to some extent) in their development. What they aren't doing is publishing their test results. I believe the biggest reason for that is that it just isn't a big enough priority. ACT needs something like a filter in the Evaluation Tools List for tool vendors to prioritise this effort.

I feel strongly that this filter needs to be in when this redesign is published. Even if awareness was an issue, which I'm not convinced by, I don't think it should influence the decision. The only thing I think should matter is whether or not ACT implementation work is sufficiently mature that people may want to use it in selecting evaluation tools. By omitting the filter, W3C is implying that ACT implementation work is not yet mature enough.

AGWG approved the ACT Implementation pages several months ago. ACT TF did a little more work on them, but has also approved them this week. We believe this is ready. If EO has additional requirements, please let us know. We'll be happy to look into that, but then I would ask for enough time to address them, instead of publishing without the ACT filter.

**Comment by bakkenb** [comment]
Thanks for the additional information Wilco. This is helpful. 

We did actually discuss in some detail EOWG feeling that it would be somewhat unfair for the list to go out with the filter prior to some public awareness communications about ACT Rules and Implementation Reports. There is a difference between "recruiting" implementers and communicating rules and reports to the general public for awareness.

We believe this is probably a non-issue though because of the timing of the publication of the list and the eminent communications that are being worked up right now about the Implementation reports. We will be able to include the filter when the list is published, and therefore we can include it in the draft now.

I think we are good on this issue.

**Comment by WilcoFiers** [comment]
I'm very glad to hear that @bakkenb!

**Comment by EricVelleman** [comment]
Agree that this is probably a non-issue because of the timing of the publication of the list (early next year if all goes well) and the eminent communications that are being worked up right now about the Implementation reports. We will put the filter back in the current draft (like it was earlier on request of the WG) if the WG agrees.

**Comment by shawna-slh** [comment]
Announced!
* [e-mail](https://lists.w3.org/Archives/Public/public-wai-announce/2022OctDec/0006.html)
* [WAI News](https://www.w3.org/WAI/news/2022-12-06/act-rules/)

**Comment by WilcoFiers** [comment]
@shawna-slh @mhansma96 This issue doesn't look like it's resolved. How come this got closed?

**Comment by EricVelleman** [comment]
> @shawna-slh @mhansma96 This issue doesn't look like it's resolved. How come this got closed?

<img width="333" alt="image" src="https://user-images.githubusercontent.com/91431056/232784874-7ae47dfa-5f11-47d5-b023-dcef65ae6148.png">

Must be a version bug, because it is resolved in the latest version in the left column: https://wai-evaluation-tools-list.netlify.app/tools-list/evaluation/

**Comment by WilcoFiers** [comment]
It's not. Accessibility Statements are not the same as the ACT Implementations filter that used to be there. Could you please reopen the issue?

**Comment by iadawn** [comment]
This appears to be addressed in the current [Netlify deploy](https://master--wai-evaluation-tools-list.netlify.app/tools-list/evaluation/) so I am closing it.
