### ISSUE TITLE
delete old data

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-evaluation-tools-list#96]
We decided not to use the old data, as one purpose of the revised list is to get fresh info.

Therefore, please delete the old data from the [draft revision](https://master--wai-evaluation-tools-list.netlify.app/tools-list/evaluation/). It would be good to do that soon since we are starting to point to the draft publicly.

It would be good to have a couple of fake entries so reviewers can see what the listings will look like. And, good to make that clearly "dummy data".

**Comment by shawna-slh** [comment]
Vera, Eric V., @mhansma96 CC: @iadawn 

Please delete the old data right away. There are problems with it. Thanks.

**Comment by mhansma96** [comment]
@shawna-slh @iadawn I received a comment from Eric to wait with this until the working group looks at it (so they can see some examples when clicking through). So to check, should we delete right now or keep for a little while?

**Comment by shawna-slh** [comment]
OK. EOWG review closes today.

> It would be good to have a couple of fake entries so reviewers can see what the listings will look like. And, good to make that clearly "dummy data".

We need to delete the data before we publicize the submission form. And also then it would be good to have some examples. I think OK if it's only a few (3+) examples. Maybe do a couple with very little data, and one that's near the bottom with lots of data?
rationale: We don't want submitters bloating their listing, so having the minimal ones at the top of the list might help that. Having one with lots of data might be useful to see how each field is shown in the list?

**Comment by shawna-slh** [comment]
I also note that having the new UI with old data led to Mary Jo doing unnecessary review and commenting in the [survey](https://www.w3.org/2002/09/wbs/35532/evaltools_butterfly/results).

**Comment by iadawn** [comment]
+1 to removing all data before Submission Form is published
-1 to leaving examples. I don't see what value that adds.

**Comment by shawna-slh** [comment]
> I don't see what value that adds.

So people submitting tools can see what the list looks like. We've been asked for that.

I did one. https://github.com/w3c/wai-evaluation-tools-list/pull/155
... but now I can't find the preview :-/ @iadawn @mhansma96

**Comment by iadawn** [comment]
@shawna-slh, a few things...

* Submissions go to the submissions folder, not the tools folder. Tools was used previously and because all the data was there, it wasn't picked up until a real submission was made
* The data format changed. Again, the old data had been being used and some changes in names and how things were handled weren't picked up
* Any time a tool is approved (by merging a PR) it will be added into the wai-evaluation-tools-list repo. Some other things would need to be done (I am assuming) to get it into the wai-website Netlify for review... I am not sure how this happens atm. To see a preview with your submitted test data see: https://657ad602b1208e0008158a90--wai-evaluation-tools-list.netlify.app/test-evaluate/tools/list/
